CONF_A35LIB_ATC_ENGINE_SPINUP_DEFAULT_TIME = 10;
CONF_A35LIB_ATC_ENGINE_FLIGHTPREPARATION_DEFAULT_TIME = 30;
CONF_A35LIB_ATC_TAXI_DEFAULT_SPEED = 7;
CONF_A35LIB_ATC_TAXI_DEFAULT_OFFSET = [0,0,0.6];
CONF_A35LIB_ATC_TAXI_DEFAULT_DESTINATION_CHECK_INTERVAL = 10;
CONF_A35LIB_ATC_TAXI_DEFAULT_DESTINATION_DISTANCE = 10;